# Generated by Django 5.2.15 on 2026-06-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("basketball", "Basketball"),
                            ("football", "Football"),
                        ],
                        max_length=20,
                    ),
                ),
                ("match_id", models.CharField(max_length=100)),
                ("parameter", models.CharField(max_length=50)),
                ("baseline", models.FloatField()),
                ("threshold", models.FloatField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projection", models.FloatField()),
                ("deviation", models.FloatField()),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.watch",
                    ),
                ),
            ],
        ),
    ]
