# Generated by Django 5.2.15 on 2026-06-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[("UP", "UP"), ("DOWN", "DOWN")], default="UP", max_length=10
            ),
            preserve_default=False,
        ),
    ]
