# Generated by Django 5.2.15 on 2026-06-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_alert_alert_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("total_points", "Total Points"),
                    ("home_points", "Home Team Points"),
                    ("away_points", "Away Team Points"),
                    ("three_points_made", "3PT Made"),
                    ("three_points_attempted", "3PT Attempted"),
                    ("two_points_made", "2PT Made"),
                    ("two_points_attempted", "2PT Attempted"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="MatchSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_points", models.FloatField()),
                ("projection", models.FloatField()),
                ("deviation", models.FloatField()),
                ("minutes_played", models.FloatField()),
                ("expected_scoring_rate", models.FloatField()),
                ("actual_scoring_rate", models.FloatField()),
                ("scoring_rate_deviation", models.FloatField()),
                ("recent_scoring_rate", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="monitoring.watch",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("points", models.IntegerField(default=0)),
                ("two_pt_made", models.IntegerField(default=0)),
                ("two_pt_attempted", models.IntegerField(default=0)),
                ("three_pt_made", models.IntegerField(default=0)),
                ("three_pt_attempted", models.IntegerField(default=0)),
                ("free_throw_made", models.IntegerField(default=0)),
                ("free_throw_attempted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.watch",
                    ),
                ),
            ],
        ),
    ]
