# Generated by Django 5.2.15 on 2026-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_alter_watch_parameter_matchsnapshot_teamstatistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchsnapshot",
            name="expected_points",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchsnapshot",
            name="live_deviation",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
