# Generated by Django 5.2.15 on 2026-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0004_matchsnapshot_expected_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="away_team",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="watch",
            name="home_team",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="watch",
            name="league",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
