# Generated by Django 5.2.15 on 2026-06-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0005_watch_away_team_watch_home_team_watch_league"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watch",
            name="baseline",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="parameter",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="threshold",
        ),
        migrations.CreateModel(
            name="WatchParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("total_points", "Total Points"),
                            ("home_points", "Home Team Points"),
                            ("away_points", "Away Team Points"),
                            ("three_points_made", "3PT Made"),
                            ("three_points_attempted", "3PT Attempted"),
                            ("two_points_made", "2PT Made"),
                            ("two_points_attempted", "2PT Attempted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("baseline", models.FloatField()),
                ("threshold", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="monitoring.watch",
                    ),
                ),
            ],
            options={
                "unique_together": {("watch", "parameter")},
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="parameter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.watchparameter",
            ),
        ),
    ]
