# Generated by Django 5.2.15 on 2026-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0006_remove_watch_baseline_remove_watch_parameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="game_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="watch",
            name="last_polled",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="watch",
            name="monitoring_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="watch",
            name="monitoring_start",
            field=models.DateTimeField(
                blank=True, help_text="Time monitoring should begin", null=True
            ),
        ),
        migrations.AddField(
            model_name="watch",
            name="monitoring_started",
            field=models.BooleanField(default=False),
        ),
    ]
