# Generated by Django 5.2.15 on 2026-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0007_watch_game_status_watch_last_polled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchsnapshot",
            name="elapsed_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matchsnapshot",
            name="game_clock",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
