# Generated by Django 5.2.15 on 2026-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0008_matchsnapshot_elapsed_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="total_game_minutes",
            field=models.IntegerField(default=40),
        ),
    ]
