# Generated by Django 5.2.15 on 2026-06-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0009_watch_total_game_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchsnapshot",
            name="bookmaker_spread",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchsnapshot",
            name="bookmaker_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="assists",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="blocks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="game_minute",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="projected_points",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="rebounds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="steals",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="team_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="turnovers",
            field=models.IntegerField(default=0),
        ),
    ]
