# Generated by Django 5.2.15 on 2026-06-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0010_matchsnapshot_bookmaker_spread_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamstatistic",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="teamstatistic",
            name="two_pt_attempted",
        ),
        migrations.RemoveField(
            model_name="teamstatistic",
            name="two_pt_made",
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="bookmaker_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="elapsed_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="estimated_possessions",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="field_goal_attempted",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="field_goal_made",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="field_goal_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="field_goal_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="free_throw_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="game_clock",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="offensive_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="pace",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="points_per_possession",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="three_pt_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="alert",
            name="parameter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="monitoring.watchparameter",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="watch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="monitoring.watch",
            ),
        ),
        migrations.AlterField(
            model_name="teamstatistic",
            name="watch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_statistics",
                to="monitoring.watch",
            ),
        ),
    ]
