# Generated by Django 5.2.15 on 2026-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0011_alter_teamstatistic_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamstatistic",
            name="game_status",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="teamstatistic",
            name="quarter",
            field=models.IntegerField(default=0),
        ),
    ]
