# Generated by Django 5.2.15 on 2026-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0012_teamstatistic_game_status_teamstatistic_quarter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="bookmaker_spread",
        ),
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="bookmaker_total",
        ),
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="deviation",
        ),
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="expected_points",
        ),
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="expected_scoring_rate",
        ),
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="live_deviation",
        ),
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="projection",
        ),
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="recent_scoring_rate",
        ),
        migrations.RemoveField(
            model_name="matchsnapshot",
            name="scoring_rate_deviation",
        ),
        migrations.AlterField(
            model_name="matchsnapshot",
            name="actual_scoring_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="matchsnapshot",
            name="current_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="matchsnapshot",
            name="minutes_played",
            field=models.FloatField(default=0),
        ),
    ]
