# Generated by Django 5.2.14 on 2026-09-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0013_remove_matchsnapshot_bookmaker_spread_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatAlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("shots_on_goal", "Shots on Goal"),
                            ("shots_off_goal", "Shots off Goal"),
                            ("total_shots", "Total Shots"),
                            ("blocked_shots", "Blocked Shots"),
                            ("shots_insidebox", "Shots Inside Box"),
                            ("shots_outsidebox", "Shots Outside Box"),
                            ("fouls", "Fouls"),
                            ("corner_kicks", "Corner Kicks"),
                            ("offsides", "Offsides"),
                            ("yellow_cards", "Yellow Cards"),
                            ("red_cards", "Red Cards"),
                            ("goalkeeper_saves", "Goalkeeper Saves"),
                            ("total_passes", "Total Passes"),
                            ("passes_accurate", "Passes Accurate"),
                            ("throw_ins", "Throw-ins"),
                            ("goal_kicks", "Goal Kicks"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "team_scope",
                    models.CharField(
                        choices=[
                            ("both", "Either team"),
                            ("home", "Home team only"),
                            ("away", "Away team only"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            (
                                "silence",
                                "Silence — alert if no new occurrence for N minutes",
                            ),
                            (
                                "burst",
                                "Burst — alert if N or more occurrences within a window",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "silence_gap_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Alert if no new occurrence of this stat for this many minutes.",
                        null=True,
                    ),
                ),
                (
                    "burst_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of occurrences that triggers a burst alert.",
                        null=True,
                    ),
                ),
                (
                    "burst_window_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rolling time window (minutes) the burst count is measured over.",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_alert_rules",
                        to="monitoring.watch",
                    ),
                ),
            ],
            options={
                "unique_together": {("watch", "stat_type", "team_scope")},
            },
        ),
        migrations.CreateModel(
            name="StatAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("silence", "Silence"), ("burst", "Burst")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_alerts",
                        to="monitoring.watch",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fired_alerts",
                        to="monitoring.statalertrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("shots_on_goal", "Shots on Goal"),
                            ("shots_off_goal", "Shots off Goal"),
                            ("total_shots", "Total Shots"),
                            ("blocked_shots", "Blocked Shots"),
                            ("shots_insidebox", "Shots Inside Box"),
                            ("shots_outsidebox", "Shots Outside Box"),
                            ("fouls", "Fouls"),
                            ("corner_kicks", "Corner Kicks"),
                            ("offsides", "Offsides"),
                            ("yellow_cards", "Yellow Cards"),
                            ("red_cards", "Red Cards"),
                            ("goalkeeper_saves", "Goalkeeper Saves"),
                            ("total_passes", "Total Passes"),
                            ("passes_accurate", "Passes Accurate"),
                            ("throw_ins", "Throw-ins"),
                            ("goal_kicks", "Goal Kicks"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        choices=[("home", "Home"), ("away", "Away")], max_length=10
                    ),
                ),
                (
                    "value_at_time",
                    models.PositiveIntegerField(
                        help_text="Cumulative stat total at the moment this occurrence was detected."
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_occurrences",
                        to="monitoring.watch",
                    ),
                ),
            ],
            options={
                "ordering": ["detected_at"],
            },
        ),
    ]
