# Generated by Django 5.2.14 on 2026-09-09 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0014_statalertrule_statalert_statoccurrence"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="statalertrule",
            unique_together={("watch", "stat_type", "team_scope", "mode")},
        ),
    ]
