# Generated by Django 5.2.14 on 2026-09-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0015_alter_statalertrule_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="statalertrule",
            name="expected_total",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Your own expected/target total for this stat by full-time (reference only).",
                null=True,
            ),
        ),
    ]
