# Generated by Django 5.2.15 on 2026-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0016_statalertrule_expected_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="elapsed_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
