# Generated by Django 5.2.15 on 2026-09-10 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0017_watch_elapsed_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatOddsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("shots_on_goal", "Shots on Goal"),
                            ("shots_off_goal", "Shots off Goal"),
                            ("total_shots", "Total Shots"),
                            ("blocked_shots", "Blocked Shots"),
                            ("shots_insidebox", "Shots Inside Box"),
                            ("shots_outsidebox", "Shots Outside Box"),
                            ("fouls", "Fouls"),
                            ("corner_kicks", "Corner Kicks"),
                            ("offsides", "Offsides"),
                            ("yellow_cards", "Yellow Cards"),
                            ("red_cards", "Red Cards"),
                            ("goalkeeper_saves", "Goalkeeper Saves"),
                            ("total_passes", "Total Passes"),
                            ("passes_accurate", "Passes Accurate"),
                            ("throw_ins", "Throw-ins"),
                            ("goal_kicks", "Goal Kicks"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "mu_0",
                    models.FloatField(
                        help_text="Pre-match expected total for this stat, from the bookmaker's own odds ladder for this match."
                    ),
                ),
                (
                    "dispersion_r",
                    models.FloatField(
                        blank=True,
                        help_text="Negative binomial dispersion for this stat. Leave blank to use the fitted per-stat default.",
                        null=True,
                    ),
                ),
                (
                    "overround",
                    models.FloatField(
                        default=1.1,
                        help_text="Bookmaker margin to reapply when pricing the live odds board, e.g. 1.10 = 10% overround.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_odds_models",
                        to="monitoring.watch",
                    ),
                ),
            ],
            options={
                "unique_together": {("watch", "stat_type")},
            },
        ),
    ]
