# Generated by Django 5.2.15 on 2026-09-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0018_statoddsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="statalert",
            name="odds_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fired_alerts",
                to="monitoring.statoddsmodel",
            ),
        ),
        migrations.AddField(
            model_name="statoddsmodel",
            name="confidence_threshold",
            field=models.FloatField(
                default=0.8,
                help_text="Fire a confidence alert once any line's fair win probability reaches this level, e.g. 0.80 = 80%.",
            ),
        ),
        migrations.AlterField(
            model_name="statalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("silence", "Silence"),
                    ("burst", "Burst"),
                    ("confidence", "Confidence"),
                ],
                max_length=10,
            ),
        ),
    ]
