# Generated by Django 5.2.15 on 2026-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0019_statalert_odds_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statalertrule",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("shots_on_goal", "Shots on Goal"),
                    ("shots_off_goal", "Shots off Goal"),
                    ("total_shots", "Total Shots"),
                    ("blocked_shots", "Blocked Shots"),
                    ("shots_insidebox", "Shots Inside Box"),
                    ("shots_outsidebox", "Shots Outside Box"),
                    ("fouls", "Fouls"),
                    ("corner_kicks", "Corner Kicks"),
                    ("offsides", "Offsides"),
                    ("yellow_cards", "Yellow Cards"),
                    ("red_cards", "Red Cards"),
                    ("goalkeeper_saves", "Goalkeeper Saves"),
                    ("total_passes", "Total Passes"),
                    ("passes_accurate", "Passes Accurate"),
                    ("throw_ins", "Throw-ins"),
                    ("goal_kicks", "Goal Kicks"),
                    ("total_goals", "Total Goals"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="statoccurrence",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("shots_on_goal", "Shots on Goal"),
                    ("shots_off_goal", "Shots off Goal"),
                    ("total_shots", "Total Shots"),
                    ("blocked_shots", "Blocked Shots"),
                    ("shots_insidebox", "Shots Inside Box"),
                    ("shots_outsidebox", "Shots Outside Box"),
                    ("fouls", "Fouls"),
                    ("corner_kicks", "Corner Kicks"),
                    ("offsides", "Offsides"),
                    ("yellow_cards", "Yellow Cards"),
                    ("red_cards", "Red Cards"),
                    ("goalkeeper_saves", "Goalkeeper Saves"),
                    ("total_passes", "Total Passes"),
                    ("passes_accurate", "Passes Accurate"),
                    ("throw_ins", "Throw-ins"),
                    ("goal_kicks", "Goal Kicks"),
                    ("total_goals", "Total Goals"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="statoddsmodel",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("shots_on_goal", "Shots on Goal"),
                    ("shots_off_goal", "Shots off Goal"),
                    ("total_shots", "Total Shots"),
                    ("blocked_shots", "Blocked Shots"),
                    ("shots_insidebox", "Shots Inside Box"),
                    ("shots_outsidebox", "Shots Outside Box"),
                    ("fouls", "Fouls"),
                    ("corner_kicks", "Corner Kicks"),
                    ("offsides", "Offsides"),
                    ("yellow_cards", "Yellow Cards"),
                    ("red_cards", "Red Cards"),
                    ("goalkeeper_saves", "Goalkeeper Saves"),
                    ("total_passes", "Total Passes"),
                    ("passes_accurate", "Passes Accurate"),
                    ("throw_ins", "Throw-ins"),
                    ("goal_kicks", "Goal Kicks"),
                    ("total_goals", "Total Goals"),
                ],
                max_length=30,
            ),
        ),
    ]
