# Generated by Django 5.2.15 on 2026-09-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0021_alter_statalertrule_stat_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statoddsmodel",
            name="confidence_threshold",
        ),
        migrations.AddField(
            model_name="statoddsmodel",
            name="odds_margin",
            field=models.FloatField(
                default=0.1,
                help_text="Acceptable drift in the live fair odds from pre_match_odds, e.g. 0.10.",
            ),
        ),
        migrations.AddField(
            model_name="statoddsmodel",
            name="pre_match_odds",
            field=models.FloatField(
                default=1.9,
                help_text="Bookmaker's actual odds for the mu_0 line before kickoff, e.g. 1.94.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statoddsmodel",
            name="variation_threshold",
            field=models.FloatField(
                default=5.0,
                help_text="Minimum swing in the live projected total (vs mu_0) required to fire an alert.",
            ),
        ),
        migrations.AlterField(
            model_name="statalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("silence", "Silence"),
                    ("burst", "Burst"),
                    ("confidence", "Confidence"),
                    ("variation", "Variation"),
                ],
                max_length=10,
            ),
        ),
    ]
