# Generated by Django 5.2.15 on 2026-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0022_remove_statoddsmodel_confidence_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statalertrule",
            name="team_scope",
            field=models.CharField(
                choices=[
                    ("both", "Either team (checked separately)"),
                    ("combined", "Combined total (both teams summed)"),
                    ("home", "Home team only"),
                    ("away", "Away team only"),
                ],
                default="both",
                max_length=10,
            ),
        ),
    ]
